import React from "react"
import Carousel from "../components/Carousel"

export default function Core(){
    return(
        <Carousel 
        title="Core Domains" 
        img1="3d-printing.png"
        url1="/explore/core-domains/3d-printing" 
        img2="welding.png"
        url2="/explore/core-domains/welding" 
        img3="embedded-systems.png"
        url3="/explore/core-domains/embedded-systems"
        img4="machine-operations.png"
        url4="/explore/core-domains/machine-operations"
        img5="robotics-automation.png"
        url5="/explore/core-domains/robotics-automation"
        img6="microcontroller-programming.png"
        url6="/explore/core-domains/microcontroller-programming"
        img7="mechatronics.png"
        url7="/explore/core-domains/mechatronics"
        img8="system-engineering.png"
        url8="/explore/core-domains/system-engineering"
        img9="metal-forming.png"
        url9="/explore/core-domains/metal-forming" 
        img10="digital-signal-processing.png"
        url10="/explore/core-domains/digital-signal-processing"
        img11="mechanical-design.png"
        url11="/explore/core-domains/mechanical-design"
        img12="pcb-designing.png"
        url12="/explore/core-domains/pcb-designing"
        img13="fgpa-programming.png"
        url13="/explore/core-domains/fgpa-programming"
        img14="internet-of-things.png"
        url14="/explore/core-domains/internet-of-things"
        img15="analog-digital-electronics.png"
        url15="/explore/core-domains/analog-digital-electronics"
        img16=""
        url16="/explore/core-domains/pcb-designing"
        />
    )
} 