const SkillsData =[

    {"category":"web-technologies",
    "skill":"frontend-development",
    "name":"John Smith",
    "technicalSkillset":"Python, Java",
    "experience":"3 years",
    "achievement":"Developed a web application for a small business.",
    "linkedin":"https://linkedin.com/in/johnsmith"},

    {"category":"web-technologies",
    "skill":"frontend-development",
    "name":"Siddhant Smith",
    "technicalSkillset":"Python, Java",
    "experience":"3 years",
    "achievement":"Developed a web application for a small business.",
    "linkedin":"linkedin.com/in/johnsmith"},

    {"category":"web-technologies",
    "skill":"frontend-development",
    "name":"Sandeep Smith",
    "technicalSkillset":"Python, Java",
    "experience":"3 years",
    "achievement":"Developed a web application for a small business.",
    "linkedin":"linkedin.com/in/johnsmith"},

    {"category":"web-technologies",
    "skill":"frontend-development",
    "name":"Rahul Smith",
    "technicalSkillset":"Python, Java",
    "experience":"3 years",
    "achievement":"Developed a web application for a small business.",
    "linkedin":"linkedin.com/in/johnsmith"},

    {"category":"web-technologies",
    "skill":"frontend-development",
    "name":"Make Smith",
    "technicalSkillset":"Python, Java",
    "experience":"3 years",
    "achievement":"Developed a web application for a small business.",
    "linkedin":"linkedin.com/in/johnsmith"},
    
    {"category":"web-technologies",
    "skill":"application-development",
    "name":"Emily Johnson",
    "technicalSkillset":"R, SQL",
    "experience":"5 years","achievement":"Implemented a machine learning model that improved accuracy by 10%.",
    "linkedin":"linkedin.com/in/emilyjohnson"},
    
    {"category":"web-technologies",
    "skill":"devops","name":"Michael Davis",
    "technicalSkillset":"HTML, CSS, JavaScript",
    "experience":"2 years","achievement":"Led a team of developers to successfully launch a mobile app.",
    "linkedin":"linkedin.com/in/michaeldavis"},
    
    {"category":"web-technologies",
    "skill":"ai-ml",
    "name":"Sarah Wilson",
    "technicalSkillset":"Python, R, SQL",
    "experience":"4 years","achievement":"Analyzed a large dataset to discover actionable insights for a client.",
    "linkedin":"linkedin.com/in/sarahwilson"},
    
    {"category":"web-technologies",
    "skill":"data-science",
    "name":"Sophia Williams",
    "technicalSkillset":"AWS, Azure, DevOps",
    "experience":"6 years",
    "achievement":"Successfully migrated a company's infrastructure to the cloud, resulting in improved scalability and cost savings.",
    "linkedin":"linkedin.com/in/sophiawilliams"},
    
    {"category":"web-technologies",
    "skill":"blockchain-development",
    "name":"William Wilson",
    "technicalSkillset":"Python, TensorFlow, scikit-learn",
    "experience":"4 years",
    "achievement":"Developed a machine learning model that improved customer churn prediction accuracy by 15%.",
    "linkedin":"linkedin.com/in/williamwilson"},
    
    {"category":"web-technologies",
    "skill":"cloud-computing",
    "name":"Emily Brown",
    "technicalSkillset":"Agile, Scrum, Jira",
    "experience":"3 years","achievement":"Led a cross-functional team to deliver a complex software project on time and within budget",
    "linkedin":"linkedin.com/in/emilybrown"},
    
    {"category":"non-technical",
    "skill":"sales",
    "name":"Emily Johnson",
    "technicalSkillset":"R, SQL",
    "experience":"5 years","achievement":"Implemented a machine learning model that improved accuracy by 10%.",
    "linkedin":"linkedin.com/in/emilyjohnson"},
    
    {"category":"non-technical",
    "skill":"ui-ux",
    "name":"Emily Johnson",
    "technicalSkillset":"R, SQL",
    "experience":"5 years","achievement":"Implemented a machine learning model that improved accuracy by 10%.",
    "linkedin":"linkedin.com/in/emilyjohnson"}
];

export default SkillsData;