import React from "react"
import { Link } from "react-router-dom"
import Cards from "../components/Cards"
import DomainCards from "../components/DomainCards"
import Carousel from "../components/Carousel"

export default function Core(){
    return(
        <Carousel 
        title="Core Technologies" 
        img1="3dprinting.png"
        url1="/explore/webtech/3dprinting" 
        img2="welding.png"
        url2="/explore/webtech/welding" 
        img3="embedded.png"
        url3="/explore/qwebtech/embedded"
        img4="machineops.png"
        url4="/explore/qwebtech/machineops"
        img5="robotics.png"
        url5="/explore/qwebtech/robotics"
        img6="microcontroller.png"
        url6="/explore/qwebtech/microcontroller"
        img7="mechatronics.png"
        url7="/explore/qwebtech/mechatronics"
        img8="sysengg.png"
        url8="/explore/qwebtech/sysengg"
        img9="fabrication.png"
        url9="/explore/webtech/fabrication" 
        img10="dsp.png"
        url10="/explore/qwebtech/dsp"
        img11="mechdesign.png"
        url11="/explore/qwebtech/mechdesign"
        img12="pcb.png"
        url12="/explore/qwebtech/pcb"
        img13="fgpa.png"
        url13="/explore/qwebtech/fgpa"
        img14="iot.png"
        url14="/explore/qwebtech/iot"
        img15="analog.png"
        url15="/explore/qwebtech/analog"
        img16=""
        url16="/explore/qwebtech/pcb"
        />
    )
} 