const SkillsData =[

    {"category":"webtech",
    "skill":"frontend",
    "name":"John Smith",
    "Technical skillset":"Python, Java",
    "experience":"3 years",
    "achievement":"Developed a web application for a small business.",
    "linkedin":"linkedin.com/in/johnsmith"},

    {"category":"webtech",
    "skill":"frontend",
    "name":"Siddhant Smith",
    "Technical skillset":"Python, Java",
    "experience":"3 years",
    "achievement":"Developed a web application for a small business.",
    "linkedin":"linkedin.com/in/johnsmith"},

    {"category":"webtech",
    "skill":"frontend",
    "name":"Sandeep Smith",
    "Technical skillset":"Python, Java",
    "experience":"3 years",
    "achievement":"Developed a web application for a small business.",
    "linkedin":"linkedin.com/in/johnsmith"},

    {"category":"webtech",
    "skill":"frontend",
    "name":"Rahul Smith",
    "Technical skillset":"Python, Java",
    "experience":"3 years",
    "achievement":"Developed a web application for a small business.",
    "linkedin":"linkedin.com/in/johnsmith"},

    {"category":"webtech",
    "skill":"frontend",
    "name":"Make Smith",
    "Technical skillset":"Python, Java",
    "experience":"3 years",
    "achievement":"Developed a web application for a small business.",
    "linkedin":"linkedin.com/in/johnsmith"},
    
    {"category":"webtech",
    "skill":"appdev",
    "name":"Emily Johnson",
    "Technical skillset":"R, SQL",
    "experience":"5 years","achievement":"Implemented a machine learning model that improved accuracy by 10%.",
    "linkedin":"linkedin.com/in/emilyjohnson"},
    
    {"category":"webtech",
    "skill":"devops","name":"Michael Davis",
    "Technical skillset":"HTML, CSS, JavaScript",
    "experience":"2 years","achievement":"Led a team of developers to successfully launch a mobile app.",
    "linkedin":"linkedin.com/in/michaeldavis"},
    
    {"category":"webtech",
    "skill":"machine",
    "name":"Sarah Wilson",
    "Technical skillset":"Python, R, SQL",
    "experience":"4 years","achievement":"Analyzed a large dataset to discover actionable insights for a client.",
    "linkedin":"linkedin.com/in/sarahwilson"},
    
    {"category":"webtech",
    "skill":"datasci",
    "name":"Sophia Williams",
    "Technical skillset":"AWS, Azure, DevOps",
    "experience":"6 years",
    "achievement":"Successfully migrated a company's infrastructure to the cloud, resulting in improved scalability and cost savings.",
    "linkedin":"linkedin.com/in/sophiawilliams"},
    
    {"category":"webtech",
    "skill":"blockchain",
    "name":"William Wilson",
    "Technical skillset":"Python, TensorFlow, scikit-learn",
    "experience":"4 years",
    "achievement":"Developed a machine learning model that improved customer churn prediction accuracy by 15%.",
    "linkedin":"linkedin.com/in/williamwilson"},
    
    {"category":"webtech",
    "skill":"cloud",
    "name":"Emily Brown",
    "Technical skillset":"Agile, Scrum, Jira",
    "experience":"3 years","achievement":"Led a cross-functional team to deliver a complex software project on time and within budget",
    "linkedin":"linkedin.com/in/emilybrown"},
    
    {"category":"nontech",
    "skill":"sales",
    "name":"Emily Johnson",
    "Technical skillset":"R, SQL",
    "experience":"5 years","achievement":"Implemented a machine learning model that improved accuracy by 10%.",
    "linkedin":"linkedin.com/in/emilyjohnson"},
    
    {"category":"nontech",
    "skill":"uiux",
    "name":"Emily Johnson",
    "Technical skillset":"R, SQL",
    "experience":"5 years","achievement":"Implemented a machine learning model that improved accuracy by 10%.",
    "linkedin":"linkedin.com/in/emilyjohnson"}
];

export default SkillsData;